@HW1NoteKeeper_HostAddress = https://localhost:5267
@noteId = REPLACE_WITH_NOTE_ID

### Get all notes
GET {{HW1NoteKeeper_HostAddress}}/NoteKeeper
Accept: application/json

### Create note
POST {{HW1NoteKeeper_HostAddress}}/NoteKeeper
Accept: application/json
Content-Type: application/json

{
  "summary": "hello world",
  "details": "GitHub Copilot Chat is a companion extension to GitHub Copilot that allows you to chat with Copilot, an AI-powered assistant that helps you write better code. With GitHub Copilot Chat, you can access two key features: Chat View: Seek Copilot's assistance for any task or question within the Chat view. Inline Refinement: Apply Copilot's suggestions directly to your code, seamlessly maintaining your workflow."
}

### Get by id
GET {{HW1NoteKeeper_HostAddress}}/NoteKeeper/{{noteId}}
Accept: application/json

### Update note (patch)
PATCH {{HW1NoteKeeper_HostAddress}}/NoteKeeper/{{noteId}}
Accept: application/json
Content-Type: application/json

{
  "summary": "hello world (updated)",
  "details": "GitHub Copilot23 Chat is a companion extension to GitHub Copilot that allows you to chat with Copilot, an AI-powered assistant that helps you write better code. With GitHub Copilot Chat, you can access two key features: Chat View: Seek Copilot's assistance for any task or question within the Chat view. Inline Refinement: Apply Copilot's suggestions directly to your code, seamlessly maintaining your workflow."
}

### Delete note
DELETE {{HW1NoteKeeper_HostAddress}}/NoteKeeper/{{noteId}}
Accept: application/json