namespace HW6NoteKeeper.Controllers
{
    /// <summary>
    /// Represents the AI response containing generated tags for a note's content.
    /// </summary>
    public class KeyTagsResponse
    {
        /// <summary>
        /// Gets or sets the list of keyword tags generated by the AI model.
        /// Each tag is a single lowercase word that captures the essence of the content.
        /// </summary>
        public List<string> Tags { get; set; } = [];
    }
}
