<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DisableOpenApiSourceGenerator>True</DisableOpenApiSourceGenerator>
    <UserSecretsId>aspnet-HW6NoteKeeper-576487b3-02c9-4daa-94c9-906c488ecc5c</UserSecretsId>
	<Optimize>false</Optimize>
	<PublishDocumentationFile>true</PublishDocumentationFile>
  </PropertyGroup>
	
  <PropertyGroup>
	<PublishTrimmed>false</PublishTrimmed>
	<PublishSingleFile>false</PublishSingleFile>
  </PropertyGroup>
	
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Swagger\**" />
    <Content Remove="Swagger\**" />
    <EmbeddedResource Remove="Swagger\**" />
    <None Remove="Swagger\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="AzureStorageAttachments\AzureLogo.png" />
    <None Remove="AzureStorageAttachments\AzureTipsAndTricks.pdf" />
    <None Remove="AzureStorageAttachments\Chocolate.png" />
    <None Remove="AzureStorageAttachments\Diamonds.png" />
    <None Remove="AzureStorageAttachments\MilkAndEggs.png" />
    <None Remove="AzureStorageAttachments\NewCar.png" />
    <None Remove="AzureStorageAttachments\Oranges.png" />
    <None Remove="AzureStorageAttachments\Tape.png" />
    <None Remove="AzureStorageAttachments\WrappingPaper.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AzureStorageAttachments\AzureLogo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="AzureStorageAttachments\AzureTipsAndTricks.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="AzureStorageAttachments\Chocolate.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="AzureStorageAttachments\Diamonds.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="AzureStorageAttachments\MilkAndEggs.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="AzureStorageAttachments\NewCar.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="AzureStorageAttachments\Oranges.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="AzureStorageAttachments\Tape.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="AzureStorageAttachments\WrappingPaper.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup> 

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.9.0-beta.1" />
    <PackageReference Include="Azure.Data.Tables" Version="12.11.0" />
    <PackageReference Include="Azure.Identity" Version="1.18.0-beta.3" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
    <PackageReference Include="Azure.Storage.Common" Version="12.27.0-beta.1" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.26.0-beta.1" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.PerfCounterCollector" Version="2.23.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.SnapshotCollector" Version="1.4.6" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0-preview3.25342.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.4.1" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.4.1" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.13.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="11.0.0-preview.2.26159.112" />
    <PackageReference Include="NJsonSchema" Version="11.5.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.4" />
  </ItemGroup> 

  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>

</Project>
